"""
scripts/build_grounded_sft.py
==============================
Build SFT training data for the 'reflect_grounded' condition using a
two-model pipeline:

  Step 1 — Student model generates wrong first attempts on training problems.
  Step 2 — Teacher model generates grounded, forced-quote reflections for
            each wrong attempt (seeing the correct answer as oracle context).
  Step 3 — Assemble (reflection_turn, retry_turn) SFT pairs and write to JSONL.

Key differences from the original reflect_full_retry curriculum:
  • The failed solution is INCLUDED in the reflection prompt (not omitted)
  • The "no digits" constraint is REMOVED — specific values are required
  • Reflections are generated by the teacher model, not a hardcoded constant
  • The forced-quote format (WRONG LINE / WHY WRONG / CORRECT VALUE) requires
    the model to cite a specific line from the failed attempt

Output:
  data/processed/curriculum/reflect_grounded.jsonl  (default)

Usage
-----
  # Generate ~2 000 grounded SFT examples (fast initial test)
  python scripts/build_grounded_sft.py \\
      --student_model Qwen/Qwen3-4B \\
      --teacher_model Qwen/Qwen3-8B \\
      --limit 1000 \\
      --out_jsonl data/processed/curriculum/reflect_grounded.jsonl

  # Larger run for production training
  python scripts/build_grounded_sft.py \\
      --student_model Qwen/Qwen3-4B \\
      --teacher_model Qwen/Qwen3-8B \\
      --limit 5000 \\
      --out_jsonl data/processed/curriculum/reflect_grounded.jsonl

The --limit cap applies to *problems attempted*, not pairs written.
Typically ~60-70% of problems yield a wrong first attempt and a parseable
grounded reflection, so --limit 1000 produces ~600-700 SFT pairs.

Resume / incremental
--------------------
Pass --resume to skip problems whose question already appears in the
output file. Safe to re-run after a partial failure.
"""

import argparse
import json
import os
import random
import re
import sys
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from dotenv import load_dotenv

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))
load_dotenv(_REPO_ROOT / ".env")

from src.rrr.rrr_infer import (
    build_reflection_prompt_grounded,
    build_retry_prompt_grounded,
    build_solve_prompt,
    normalize_answer,
    parse_pred_final,
)
from src.utils.answer_parser import math_strict_equal


# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------

def build_teacher_prompt(
    question: str,
    failed_solution: str,
    pred_final: str,
    gt_final: str,
    dataset: str,
) -> str:
    """
    Teacher-model prompt: includes the correct answer as oracle context so the
    teacher can generate a maximally informative grounded reflection.
    """
    return (
        "You are generating training data for a math tutoring model.\n"
        "A student solved a problem incorrectly. "
        "Identify the FIRST calculation mistake in their work.\n\n"
        f"Problem:\n{question}\n\n"
        f"Student's wrong attempt:\n{failed_solution}\n\n"
        f"Student's (wrong) answer: {pred_final}\n"
        f"Correct answer: {gt_final}\n\n"
        "Generate a reflection in EXACTLY this format (3 lines, nothing else):\n"
        'WRONG LINE: "<copy the exact line from the wrong attempt where the first error occurs>"\n'
        "WHY WRONG: <one sentence explaining the specific arithmetic or algebraic error>\n"
        "CORRECT VALUE: <what the result of that line should actually be>\n\n"
        "Rules:\n"
        "- WRONG LINE must be verbatim from the wrong attempt (put it in quotes)\n"
        "- Be specific about numbers (e.g. 'got 48 but should be 24')\n"
        "- Focus on the FIRST error, not the final answer\n"
        "- Output ONLY the 3 lines, nothing else\n"
    )


# ---------------------------------------------------------------------------
# Reflection validator
# ---------------------------------------------------------------------------

# Accept WRONG LINE with or without surrounding quotes.
# Group 1 captures quoted content; group 2 captures unquoted content.
_WRONG_LINE_RE  = re.compile(r'^WRONG LINE:\s*(?:"(.+?)"|(.+))', re.MULTILINE)
_WHY_WRONG_RE   = re.compile(r'^WHY WRONG:\s*(.+)',    re.MULTILINE)
_CORRECT_VAL_RE = re.compile(r'^CORRECT VALUE:\s*(.+)', re.MULTILINE)


def parse_grounded_reflection(text: str) -> Optional[str]:
    """
    Return a normalised reflection string if the teacher output contains all
    three required fields, else None.

    Accepts WRONG LINE with or without double-quote wrapping, since models
    often omit the quotes despite being instructed to include them.
    The output is always normalised to include quotes around WRONG LINE.
    """
    text = (text or "").strip()

    wl  = _WRONG_LINE_RE.search(text)
    ww  = _WHY_WRONG_RE.search(text)
    cv  = _CORRECT_VAL_RE.search(text)

    if not (wl and ww and cv):
        return None

    # Prefer quoted capture group, fall back to unquoted
    wrong_line    = (wl.group(1) or wl.group(2) or "").strip().strip('"').strip()
    why_wrong     = ww.group(1).strip()
    correct_value = cv.group(1).strip()

    # Reject generic / empty WRONG LINE values
    if len(wrong_line) < 4:
        return None
    if wrong_line.lower() in ("<line>", "<quote>", "unknown", "n/a", ""):
        return None

    # Normalise output: always wrap WRONG LINE in quotes
    return (
        f'WRONG LINE: "{wrong_line}"\n'
        f"WHY WRONG: {why_wrong}\n"
        f"CORRECT VALUE: {correct_value}"
    )


# ---------------------------------------------------------------------------
# SFT pair builder
# ---------------------------------------------------------------------------

def make_sft_pair(
    question: str,
    failed_solution: str,
    pred_final: str,
    grounded_reflection: str,
    gt_target: str,
    dataset: str,
    difficulty: int,
    question_id: str,
) -> List[Dict]:
    """Return [reflection_turn, retry_turn] SFT examples."""
    refl_prompt  = build_reflection_prompt_grounded(question, failed_solution, pred_final)
    retry_prompt = build_retry_prompt_grounded(question, grounded_reflection, dataset)

    meta = {
        "id":         question_id,
        "dataset":    dataset,
        "mode":       "reflect_grounded",
        "difficulty": difficulty,
    }

    return [
        {
            "messages": [
                {"role": "user",      "content": refl_prompt},
                {"role": "assistant", "content": grounded_reflection},
            ],
            "metadata": {**meta, "stage": "reflection"},
        },
        {
            "messages": [
                {"role": "user",      "content": retry_prompt},
                {"role": "assistant", "content": gt_target},
            ],
            "metadata": {**meta, "stage": "retry"},
        },
    ]


# ---------------------------------------------------------------------------
# Tinker helpers
# ---------------------------------------------------------------------------

def _make_sampling_client(service, tokenizer_holder, tinker, types, base_model: str):
    """
    Create a base-model sampling client (no LoRA fine-tuning).
    Returns (sampling_client, tokenizer).
    """
    # Tinker requires at least one trainable component even for inference-only use.
    # We set train_attn=True but never call forward_backward, so weights stay at
    # base-model initialisation — this is effectively base-model inference.
    tc = service.create_lora_training_client(
        base_model=base_model,
        rank=8,
        seed=42,
        train_attn=True,
        train_mlp=False,
        train_unembed=False,
    )
    tok = tc.get_tokenizer()
    # Use a timestamp suffix to avoid Tinker name collisions across re-runs.
    unique_name = f"grounded-sft-{base_model.split('/')[-1]}-{int(time.time())}"
    sc  = tc.save_weights_and_get_sampling_client(name=unique_name)
    return sc, tok


def _apply_chat_template(tokenizer, prompt: str) -> str:
    """Convert a raw prompt string to the model's chat format."""
    msgs = [{"role": "user", "content": prompt}]
    if hasattr(tokenizer, "apply_chat_template"):
        return tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
    return prompt


def _sample(sc, tokenizer, tinker, types, prompt: str,
            max_new_tokens: int = 512, temperature: float = 0.7,
            top_p: float = 0.95, seed: int = 42) -> str:
    """Sample one completion from a Tinker sampling client."""
    try:
        prompt_ids = tokenizer.apply_chat_template(
            [{"role": "user", "content": prompt}],
            tokenize=True, add_generation_prompt=True, return_tensors=None,
        )
    except Exception:
        prompt_ids = tokenizer.encode(prompt, add_special_tokens=True)
    if hasattr(prompt_ids, "tolist"):
        prompt_ids = prompt_ids.tolist()
    fut = sc.sample(
        prompt=types.ModelInput.from_ints(prompt_ids),
        num_samples=1,
        sampling_params=tinker.SamplingParams(
            max_tokens=max_new_tokens,
            temperature=temperature,
            top_p=top_p,
            seed=seed,
        ),
    )
    result = fut.result()
    ids = result.sequences[0].tokens
    return tokenizer.decode(ids, skip_special_tokens=True).strip()


# ---------------------------------------------------------------------------
# Data loading helpers
# ---------------------------------------------------------------------------

def load_jsonl(path: str) -> List[Dict]:
    rows = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def _difficulty_gsm8k(answer_str: str) -> int:
    count = len(re.findall(r"<<[^>]+>>", answer_str or ""))
    if count <= 1: return 1
    if count == 2: return 2
    if count == 3: return 3
    if count == 4: return 4
    return 5


def _difficulty_math(level_str: str) -> int:
    m = re.search(r"(\d+)", level_str or "")
    return max(1, min(5, int(m.group(1)))) if m else 3


def _extract_gsm8k_final(answer_str: str) -> Optional[str]:
    m = re.search(r"####\s*(.+)$", (answer_str or "").strip(), re.MULTILINE)
    if m:
        return m.group(1).strip()
    lines = [l.strip() for l in (answer_str or "").splitlines() if l.strip()]
    return lines[-1] if lines else None


def _format_gold_target(dataset: str, ex: Dict) -> Optional[str]:
    if dataset == "gsm8k":
        final = _extract_gsm8k_final(ex.get("answer", ""))
        return f"#### {final}" if final else None
    ans = str(ex.get("answer", "")).strip()
    return f"\\boxed{{{ans}}}" if ans else None


def prepare_problems(
    gsm_path: str,
    math_path: str,
    limit: int,
    seed: int,
) -> List[Tuple]:
    """
    Load and sample training problems.
    Returns list of (dataset, question, gt_final, gold_target, difficulty, qid) tuples.
    """
    rng = random.Random(seed)
    problems = []

    # GSM8K
    for i, ex in enumerate(load_jsonl(gsm_path)):
        q    = ex.get("question", "")
        ans  = ex.get("answer", "")
        gt   = _extract_gsm8k_final(ans)
        gold = _format_gold_target("gsm8k", ex)
        diff = _difficulty_gsm8k(ans)
        if q and gt and gold:
            problems.append(("gsm8k", q, gt, gold, diff, f"gsm8k-train-{i}"))

    # MATH
    for i, ex in enumerate(load_jsonl(math_path)):
        q    = ex.get("question", "")
        ans  = str(ex.get("answer", "")).strip()
        gold = _format_gold_target("math", ex)
        gt   = ans
        diff = _difficulty_math(ex.get("level", ""))
        if q and gt and gold:
            problems.append(("math", q, gt, gold, diff, f"math-train-{i}"))

    rng.shuffle(problems)
    return problems[:limit]


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(
        description="Build grounded SFT data using a two-model teacher pipeline.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    ap.add_argument("--student_model", default="Qwen/Qwen3-4B-Instruct-2507",
                    help="Model used to generate wrong first attempts.")
    ap.add_argument("--teacher_model", default="Qwen/Qwen3-8B",
                    help="Stronger model used to generate grounded reflections.")
    ap.add_argument("--gsm_in",  default="data/processed/gsm8k_train.jsonl")
    ap.add_argument("--math_in", default="data/processed/math_train.jsonl")
    ap.add_argument("--out_jsonl",
                    default="data/processed/curriculum/reflect_grounded.jsonl")
    ap.add_argument("--limit",  type=int, default=2000,
                    help="Number of training problems to attempt.")
    ap.add_argument("--seed",   type=int, default=42)
    ap.add_argument("--resume", action="store_true",
                    help="Skip questions already present in --out_jsonl.")
    ap.add_argument("--student_temperature", type=float, default=0.8,
                    help="Temperature for student model (higher = more wrong attempts).")
    ap.add_argument("--teacher_temperature", type=float, default=0.3,
                    help="Temperature for teacher reflection generation.")
    ap.add_argument("--max_solve_tokens",   type=int, default=512)
    ap.add_argument("--max_reflect_tokens", type=int, default=256)
    args = ap.parse_args()

    if not os.getenv("TINKER_API_KEY"):
        raise RuntimeError("TINKER_API_KEY not set in .env")

    import tinker
    from tinker import types

    out_path = _REPO_ROOT / args.out_jsonl
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # -- Resume: load already-processed questions --------------------------------
    already_done: set = set()
    if args.resume and out_path.exists():
        with out_path.open(encoding="utf-8") as f:
            for line in f:
                row = json.loads(line)
                if row.get("metadata", {}).get("stage") == "reflection":
                    msgs = row.get("messages", [])
                    if msgs:
                        already_done.add(msgs[0]["content"][:120])
        print(f"[resume] {len(already_done)} questions already processed — skipping.")

    # -- Load problems -----------------------------------------------------------
    print(f"\n[data] Loading training problems (limit={args.limit}) ...")
    gsm_path  = str(_REPO_ROOT / args.gsm_in)
    math_path = str(_REPO_ROOT / args.math_in)
    problems  = prepare_problems(gsm_path, math_path, args.limit, args.seed)
    print(f"[data] {len(problems)} problems loaded.")

    # -- Create Tinker clients ---------------------------------------------------
    service = tinker.ServiceClient()

    print(f"\n[tinker] Creating student sampling client ({args.student_model}) ...")
    try:
        student_sc, student_tok = _make_sampling_client(
            service, None, tinker, types, args.student_model
        )
    except Exception as exc:
        print(f"\n[FATAL] Student client creation failed: {type(exc).__name__}: {exc}")
        raise
    print("[tinker] Student client ready.")

    same_model = (args.student_model == args.teacher_model)
    if same_model:
        teacher_sc, teacher_tok = student_sc, student_tok
        print("[tinker] Teacher = student (same model).")
    else:
        print(f"[tinker] Creating teacher sampling client ({args.teacher_model}) ...")
        try:
            teacher_sc, teacher_tok = _make_sampling_client(
                service, None, tinker, types, args.teacher_model
            )
        except Exception as exc:
            print(f"\n[FATAL] Teacher client creation failed: {type(exc).__name__}: {exc}")
            raise
        print("[tinker] Teacher client ready.")

    # -- Main loop ---------------------------------------------------------------
    n_attempted  = 0
    n_wrong      = 0
    n_parsed     = 0
    n_written    = 0

    out_f = out_path.open("a", encoding="utf-8")

    try:
        for idx, (dataset, question, gt_final, gold_target, difficulty, qid) in enumerate(problems):

            # Resume check
            solve_prompt_prefix = build_solve_prompt(question, dataset)[:120]
            if solve_prompt_prefix in already_done:
                continue

            n_attempted += 1

            if n_attempted % 50 == 1:
                print(f"\n[{n_attempted}/{len(problems)}] pairs_written={n_written}  "
                      f"wrong_rate={n_wrong/max(n_attempted,1):.0%}  "
                      f"parse_rate={n_parsed/max(n_wrong,1):.0%}")

            # ── Step 1: Student generates a first attempt ────────────────────────
            solve_prompt = build_solve_prompt(question, dataset)
            try:
                student_answer = _sample(
                    student_sc, student_tok, tinker, types,
                    solve_prompt,
                    max_new_tokens=args.max_solve_tokens,
                    temperature=args.student_temperature,
                    top_p=0.95,
                    seed=args.seed + idx,
                )
            except Exception as exc:
                print(f"  [warn] student sample failed ({qid}): {exc}")
                continue

            # Parse student answer
            p = parse_pred_final(student_answer)
            pred_final_str = p.get("loose") or p.get("strict") or ""

            # Check if wrong — compare pred against gt_final string directly.
            # parse_gt_final / strict_match expect a full example dict; here
            # we have plain strings, so use the lower-level helpers instead.
            pred_strict = parse_pred_final(student_answer).get("strict", "")
            if dataset == "math":
                ok = math_strict_equal(pred_strict, gt_final)
            else:
                ok = normalize_answer(pred_strict) == normalize_answer(gt_final)
            if ok:
                # Correct first attempt — no reflection signal, skip
                continue
            n_wrong += 1

            # ── Step 2: Teacher generates grounded reflection ────────────────────
            teacher_prompt = build_teacher_prompt(
                question, student_answer, pred_final_str, gt_final, dataset
            )
            try:
                raw_reflection = _sample(
                    teacher_sc, teacher_tok, tinker, types,
                    teacher_prompt,
                    max_new_tokens=args.max_reflect_tokens,
                    temperature=args.teacher_temperature,
                    top_p=0.95,
                    seed=args.seed + idx + 10_000,
                )
            except Exception as exc:
                print(f"  [warn] teacher sample failed ({qid}): {exc}")
                continue

            # Validate format
            grounded_reflection = parse_grounded_reflection(raw_reflection)
            if grounded_reflection is None:
                # Teacher didn't follow the format — skip
                continue
            n_parsed += 1

            # ── Step 3: Write SFT pair ───────────────────────────────────────────
            pairs = make_sft_pair(
                question=question,
                failed_solution=student_answer,
                pred_final=pred_final_str,
                grounded_reflection=grounded_reflection,
                gt_target=gold_target,
                dataset=dataset,
                difficulty=difficulty,
                question_id=qid,
            )
            for pair in pairs:
                out_f.write(json.dumps(pair, ensure_ascii=False) + "\n")
            out_f.flush()
            n_written += len(pairs)

    finally:
        out_f.close()

    print(f"\n{'='*60}")
    print(f"  Problems attempted   : {n_attempted}")
    print(f"  Wrong first attempts : {n_wrong}  ({n_wrong/max(n_attempted,1):.0%})")
    print(f"  Parsed reflections   : {n_parsed}  ({n_parsed/max(n_wrong,1):.0%} of wrong)")
    print(f"  SFT pairs written    : {n_written // 2}  ({n_written} total turns)")
    print(f"  Output               : {out_path}")
    print(f"{'='*60}")

    if n_written == 0:
        print("\n[FATAL] No SFT pairs were written. Exiting with error to stop pipeline.")
        sys.exit(1)


if __name__ == "__main__":
    main()
